### PR TITLE
Fixes problems with old versions

### PR DESCRIPTION
**Pull request by JJ**
Basically refactors Exception to be GenericException, and CORE::Exception to simply be Exception.
Also adds checking for different versions of Raku, to avoid coming back again to fix the same problem.

### CODE REVIEW

**Comment by JJ** [comment]
I see it's not working anyway for old versions due to the use of `.DateTime`. So I'll have another way to compatibility.

**Comment by Leont** [comment]
> Basically refactors Exception to be GenericException, and CORE::Exception to simply be Exception.

Right, I had misremembered the details of that. Though I rather hate the name `GenericException` so I think I need an alternative.

**Comment by jjatria** [comment]
As far as alternatives go, how about `X::Getopt::Long`? It would mean either getting rid of the `unit`, or moving the exception into its own file and list it in the `provides`, and I can imagine objections being raised for both of those

**Comment by 2colours** [comment]
Not sure if this PR is still savable...

Is there anything worth keeping from it? Maybe there should be a new PR from that content in that case.

**Pull request closed without merging**
